routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::post('/my-logout', 'yoursessioncontroller@logout')->name('my.logout');

Route::get('/', 'HomeController@home')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/profile.html', 'HomeController@index')->name('cabinet');
    Route::get('/history.html/{paginate?}', 'HomeController@history')->name('history');
    Route::get('/business.html', 'HomeController@businessAccount')->name('business');
    Route::post('/send_preview.html', 'HomeController@payment')->name('payment');
    Route::post('/send_money.html', 'HomeController@editPayment')->name('edit');
    Route::get('/send_money/{segment2}', 'HomeController@sendInternPayment')->name('send_intern');
    Route::post('/result.html', 'HomeController@runPayment')->name('run.payment');
    Route::get('/security.html', 'HomeController@security')->name('security');
    Route::post('/change_security', 'HomeController@change_security');
    Route::get('/send.html', 'HomeController@internPayment')->name('intern');

    Route::group(['prefix' => 'dashboard'], function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::get('/account', 'DashboardController@account')->name('account');
        Route::get('/info-edit/{user}', 'DashboardController@editInfo')->name('info.edit');
        Route::post('/update-info', 'DashboardController@updateInfo')->name('update.info');
        Route::resource('wallet', 'DashboardController');
        Route::resource('log', 'LogController');
        Route::get('create-range', 'LogController@createRange')->name('log.create.range');
        Route::post('store-range', 'LogController@storeRange')->name('store.range');
        Route::get('clear-all-history', 'LogController@clear')->name('log.clear.all');
    });
	
	Route::post('/edit-wrn', 'DashboardController@updateWrn');		
	
});

app/Log.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Log extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'type_id',
        'action_id',
        'amount',
        'ip',
        'from_wallet',
        'to_wallet',
        'batch',
        'memo',
        'status',
        'wallet_type_id',
        'sort_date',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function type()
    {
        return $this->hasOne(LogType::class, 'id', 'type_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function action()
    {
        return $this->hasOne(LogAction::class, 'id', 'action_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function wallet_type()
    {
        return $this->hasOne(WalletType::class, 'id', 'wallet_type_id');
    }
}

app/LogAction.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class LogAction extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title'
    ];
}

app/LogType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class LogType extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title'
    ];
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Wallet;
use App\WalletType;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class DashboardController extends Controller
{
    public function index()
    {
        $wallets = Wallet::all();

        return view('dashboard.index', compact('wallets'));
    }

    public function create()
    {
        $type = WalletType::pluck('title', 'id');

        return view('dashboard.wallet.form', compact('type'));
    }

    public function store(Request $request)
    {
        Wallet::create([
            'title' => $request->title,
            'amount' => $request->amount,
            'type_id' => $request->type,
            'status' => isset($request->status) ? 1 : 0,

        ]);

        return redirect()->route('dashboard');
    }

    public function update(Request $request, Wallet $wallet)
    {
        $wallet->update([
            'title' => $request->title,
            'amount' => $request->amount,
            'type_id' => $request->type,
            'status' => isset($request->status) ? 1 : 0,
        ]);

        return redirect()->route('dashboard');
    }

    public function edit(Wallet $wallet)
    {
        $type = WalletType::pluck('title', 'id');

        return view('dashboard.wallet.form', compact('type', 'wallet'));
    }

    public function destroy(Wallet $wallet)
    {
        $wallet->delete();

        return redirect()->route('dashboard');
    }

    public function account()
    {
        $user = User::first();
        $status = DB::table('wallet_status')->first();
		$wrn_status = DB::table('wrn_message')->first();

        return view('dashboard.info', compact('user', 'status', 'wrn_status'));
    }

    public function editInfo(User $user)
    {
        $status = DB::table('wallet_status')->first();

        return view('dashboard.edit', compact('user', 'status'));
    }

    public function updateInfo(Request $request)
    {
        $user = User::first();

        $user->update([
            'first_name' => $request->first_name,
            'last_name' => $request->last_name,
            'father_name' => $request->father_name,
            'trust_score' => $request->trust_score,
            'nickname_client' => $request->nickname_client,
            'business_account' => isset($request->business_account) ? $request->business_account : 0,
            'verified_account' => isset($request->verified_account) ? $request->verified_account : 0,
        ]);

        DB::table('wallet_status')->update([
            'business_account' => isset($request->business_account_w) ? $request->business_account_w : 0,
            'verified_account' => isset($request->verified_account_w) ? $request->verified_account_w : 0,
            'trust_score' => $request->trust_score_w,
        ]);

        return redirect()->route('account');
    }
    public function updateWrn(Request $request)
    {
        $wrn = DB::table('wrn_message')->first();
		
        (int)$wrn->wrn == 1 ? $new_status = 0 : $new_status = 1;

        DB::table('wrn_message')->update([
            'wrn' => $new_status
        ]);
		
		return response()->json(array('response'=>true));		
    }
}

app/Http/Controllers/LogController.php
<?php

namespace App\Http\Controllers;

use App\Log;
use App\LogAction;
use App\LogType;
use App\Wallet;
use App\WalletType;
use Carbon\Carbon;
use Illuminate\Http\Request;

class LogController extends Controller
{
    public function index()
    {
        $logs = Log::with('wallet_type', 'action', 'type')->orderBy('sort_date', 'desc')->get();

        return view('dashboard.log.index', [
            'logs' => $logs
        ]);
    }

    public function create()
    {
        $type = LogType::pluck('title', 'id');
        $action = LogAction::pluck('title', 'id');
        $walletType = WalletType::pluck('title', 'id');
        $wallets = Wallet::get();

        return view('dashboard.log.form', [
            'walletType' => $walletType,
            'action' => $action,
            'type' => $type,
            'wallets' => $wallets
        ]);
    }

    public function store(Request $request)
    {
        $data = $request->except('_token');
        if (isset($data['sort_date'])) {
            if (!is_null($data['sort_date'])) {
                $time = $data['sort_time'];
                $data['sort_date'] = Carbon::parse($data['sort_date'])->format("Y-m-d $time");
            }
        }
        if ($data['ip'] == '') {
            $data['ip'] = '95.63.*.*';
        }

        Log::create($data);
        if (isset($data['to_wallet'])) {
            $wallet = Wallet::whereTitle($data['to_wallet'])->first();
            if (!is_null($wallet)) {
                $wallet->update([
                    'amount' => $wallet->amount + $data['amount']
                ]);
            }
        }

        return redirect()->route('log.index');
    }

    public function update(Request $request, Log $log)
    {
        $data = $request->except('_token', '_method');
        if (isset($data['sort_date'])) {
            if (!is_null($data['sort_date'])) {
                $time = $data['sort_time'];
                $data['sort_date'] = Carbon::parse($data['sort_date'])->format("Y-m-d $time");
            }
        }
        $log->update($data);

        return redirect()->route('log.index');
    }

    public function edit(Log $log)
    {
        $type = LogType::pluck('title', 'id');
        $action = LogAction::pluck('title', 'id');
        $walletType = WalletType::pluck('title', 'id');
        $wallets = Wallet::get();

        return view('dashboard.log.form', [
            'log' => $log,
            'walletType' => $walletType,
            'action' => $action,
            'type' => $type,
            'wallets' => $wallets
        ]);
    }

    public function destroy(Log $log)
    {
        $log->delete();

        return redirect()->route('log.index');
    }

    public function createRange()
    {
        $type = LogType::pluck('title', 'id');
        $action = LogAction::pluck('title', 'id');
        $walletType = WalletType::pluck('title', 'id');
        $wallets = Wallet::get();

        return view('dashboard.log.range', [
            'walletType' => $walletType,
            'action' => $action,
            'type' => $type,
            'wallets' => $wallets
        ]);
    }

    public function storeRange(Request $request)
    {
        $data = $request->except('_token');
        $batch = $data['batch'];

        $begin = Carbon::parse($data['form_date']);
        $end = Carbon::parse($data['to_date']);

        while ($begin <= $end){
            $time = rand($data['from_hour'], $data['to_hour']) . ':' . rand(0, 59);
            Log::create([
                'type_id' => 2,
                'action_id' => $data['action_id'],
                'amount' => $data['amount'],
                'ip' => '',
                'from_wallet' => $data['from_wallet'],
                'to_wallet' => $data['to_wallet'],
                'batch' => $batch,
                'memo' => $data['memo'],
                'sort_date' => Carbon::parse($begin)->format("Y-m-d $time"),
                'status' => 1,
                'wallet_type_id' => 2,
            ]);
            $begin = $begin->addDay();
            $batch += $data['step_batch'];
        }

        return redirect()->route('log.index');
    }

    /**
     * @param $min
     * @param $max
     * @return Carbon
     */
    public function randomDate($min, $max)
    {
        $year = rand(Carbon::parse($min)->format('y'), Carbon::parse($max)->format('y')) + 2000;
        $month = rand(Carbon::parse($min)->format('m'), Carbon::parse($max)->format('m'));
        $day = rand(Carbon::parse($min)->format('d'), Carbon::parse($max)->format('d'));
        $hour = rand(0, 23);
        $minute = rand(0, 59);

        return Carbon::create($year, $month, $day, $hour, $minute)->format('Y-m-d H:i:s');
    }

    /**
     * @return \Illuminate\Http\RedirectResponse
     */
    public function clear()
    {
        $lastLogin = Log::orderBy('created_at', 'desc')->where('action_id', 10)->first()->id;
        Log::whereNotIn('id', [$lastLogin])->delete();

        return back();
    }
}

resources/views/dashboard/log/form.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-auto">
                <div class="card">
                    <div class="card-header">Your wallets</div>

                    <div class="card-body">
                        <ul>
                            @foreach($wallets as $wallet)
                                <li>{{$wallet->title . ' - ' . $wallet->amount}}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body">
                        <form method="post"
                              action="{{isset($log) ? route('log.update', ['id' => $log->id]) : route('log.store')}}">
                            @csrf
                            @if(isset($log))
                                @method('put')
                            @endif
                            <div class="form-row">
                                <div class="form-group col-md-4">
                                    <label for="inputCity">Action</label>
                                    <select id="inputState" name="action_id" class="form-control" required>
                                        <option value="{{null}}"></option>
                                        @foreach($action as $id => $title)
                                            <option value="{{$id}}" {{isset($log) ? !is_null($log->action_id) ? $log->action_id==$id ? 'selected' : '' : '' : ''}}>{{$title}}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="inputState">Type</label>
                                    <select id="inputState" name="type_id" class="form-control" required>
                                        <option value="{{null}}"></option>
                                        @foreach($type as $id => $title)
                                            <option value="{{$id}}" {{isset($log) ? !is_null($log->type_id) ? $log->type_id==$id ? 'selected' : '' : '' : ''}}>{{$title}}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="inputZip">Amount</label>
                                    <input type="text" value="{{isset($log) ? $log->amount : ''}}" name="amount"
                                           class="form-control" id="inputZip">
                                </div>
                            </div>

                            <div class="form-row">
                                <div class="form-group col-md-4">
                                    <label for="inputZip">From Wallet</label>
                                    <input type="text" value="{{isset($log) ? $log->from_wallet : ''}}"
                                           name="from_wallet"
                                           class="form-control">
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="inputZip">To Wallet</label>
                                    <input type="text" value="{{isset($log) ? $log->to_wallet : ''}}" name="to_wallet"
                                           class="form-control" autocomplete="off">
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="inputState">Wallet type</label>
                                    <select id="inputState" name="wallet_type_id" class="form-control">
                                        <option value="{{null}}"></option>
                                        @foreach($walletType as $id => $title)
                                            <option value="{{$id}}" {{isset($log) ? !is_null($log->wallet_type_id) ? $log->wallet_type_id==$id ? 'selected' : '' : '' : ''}}>{{$title}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="form-row">
                                <div class="form-group col-md-4">
                                    <label for="inputZip">Memo</label>
                                    <input type="text" value="{{isset($log) ? $log->memo : ''}}" name="memo"
                                           class="form-control">
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="inputZip">Batch</label>
                                    <input type="text" value="{{isset($log) ? $log->batch : ''}}" name="batch"
                                           class="form-control">
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="inputZip">Ip</label>
                                    <input type="text" value="{{isset($log) ? $log->ip : ''}}" placeholder="95.63.*.*"
                                           name="ip"
                                           class="form-control">
                                </div>
                            </div>

                            <div class="form-row">
                                <div class="form-group col-md-2">
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" name="status"
                                               value="1" {{isset($log) ? (($log->status==1) ? 'checked' : '') : ''}} >
                                        <label>Status</label>
                                    </div>
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="inputZip">Date</label>
                                    {{--<input type="datetime-local" name="sort_date">--}}
                                    <input type="text" name="sort_date" value="{{isset($log) ? \Carbon\Carbon::parse($log->sort_date)->format('d.m.Y') : ''}}" size="10" class="xcalend custom_style_calendar"  onClick="xCal(this)" onmouseenter="xCal(this)" onKeyUp="xCal()">
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="inputZip">Time</label>
                                    {{--<input type="datetime-local" name="sort_date">--}}
                                    <input type="text" name="sort_time" value="{{isset($log) ? \Carbon\Carbon::parse($log->sort_date)->format('H:i') : ''}}" placeholder="15:32" size="10">
                                </div>
                            </div>

                            <input type="submit" value="Save">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        xCal("date8", {
            id: "cssworldru8", // Задать уникальный ID
            "class": "xcalend", // CSS класс оформления внешнего вида
            hide: 1, // Не скрывать календарь
            x: 0, // Отключить кнопку закрытия календаря
            autoOff: 0, // Отключить автоматическое скрытие
            to: "date8", // Разместить календарь внутри элемента с id=date8
            fn: "alert" // Вызвать функцию с указанным названием, в нее будет передан результат выбора
        });
    </script>
@endsection

resources/views/dashboard/log/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body">
                        <table class="table table-hover table-dark">
                            <thead>
                            <tr>
                                <th scope="col">Type</th>
                                <th scope="col">Action</th>
                                <th scope="col">From wallet</th>
                                <th scope="col">To wallet</th>
                                <th scope="col">Amount</th>
                                <th scope="col">Wallet type</th>
                                <th scope="col">Batch</th>
                                <th scope="col">Memo</th>
                                <th scope="col">Ip</th>
                                <th scope="col">Date</th>
                                <th scope="col">Status</th>
                                <th scope="col" colspan="2">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($logs as $log)
                                <tr>
                                    <td>{{$log->type->title}}</td>
                                    <td>{{$log->action->title}}</td>
                                    <td>{{$log->from_wallet}}</td>
                                    <td>{{$log->to_wallet}}</td>
                                    <td>{{$log->amount}}</td>
                                    <td>{{!is_null($log->wallet_type) ? $log->wallet_type->title : ""}}</td>
                                    <td>{{$log->batch}}</td>
                                    <td>{{$log->memo}}</td>
                                    <td>{{$log->ip}}</td>
                                    <td>{{$log->sort_date}}</td>
                                    <td>{{$log->status ? 'Active' : 'Disabled'}}</td>
                                    <td><a class="btn btn-warning" href="{{route('log.edit', ['id' => $log->id])}}">Edit</a>
                                    <td>
                                        <form id="delete_form_log{{$log->id}}" method="post"
                                              action="{{route('log.destroy', ['log' => $log->id])}}">
                                            @method('DELETE')
                                            @csrf
                                            <a class="btn btn-danger" style="cursor: pointer"
                                               onclick="document.getElementById('delete_form_log{{$log->id}}').submit()">Delete</a>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/log/range.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-auto">
                <div class="card">
                    <div class="card-header">Your wallets</div>

                    <div class="card-body">
                        <ul>
                            @foreach($wallets as $wallet)
                                <li>{{$wallet->title . ' - ' . $wallet->amount}}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body">
                        <form method="post"
                              action="{{route('store.range')}}">
                            @csrf
                            <div class="form-row">
                                <div class="form-group col-md-4">
                                    <label for="inputCity">Action</label>
                                    <select id="inputState" name="action_id" class="form-control" required>
                                        <option value="{{null}}"></option>
                                        @foreach($action as $id => $title)
                                            <option value="{{$id}}">{{$title}}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="inputZip">From Wallet</label>
                                    {{--<select id="inputState" name="from_wallet" class="form-control" required>--}}
                                        {{--<option value="{{null}}"></option>--}}
                                        {{--@foreach($wallets as $wallet)--}}
                                            {{--<option value="{{$wallet->title}}">{{$wallet->title . ' - '}}{{$wallet->amount}}</option>--}}
                                        {{--@endforeach--}}
                                    {{--</select>--}}
                                    <input type="text" value="" name="from_wallet" placeholder="U76334113"
                                           class="form-control">
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="inputZip">To Wallet</label>
                                    <select id="inputState" name="to_wallet" class="form-control" required>
                                        <option value="{{null}}"></option>
                                        @foreach($wallets as $wallet)
                                            <option value="{{$wallet->title}}">{{$wallet->title . ' - '}}{{$wallet->amount}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="inputState">Amount</label>
                                    <input type="text" value="" name="amount" placeholder="12132456"
                                           class="form-control">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="inputZip">Memo</label>
                                    <input type="text" value="" name="memo" placeholder="Robo-global"
                                           class="form-control">
                                </div>
                            </div>

                            <div class="form-row">

                                <div class="form-group col-md-4">
                                    <label for="inputZip">Batch</label>
                                    <input type="text" value="" name="batch" placeholder="12132456"
                                           class="form-control">
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="inputZip">Step batch</label>
                                    <input type="text" value="" placeholder="100"
                                           name="step_batch"
                                           class="form-control">
                                </div>
                            </div>

                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="inputZip">From date</label>
                                    <input type="text" name="form_date" value="{{isset($log) ? \Carbon\Carbon::parse($log->sort_date)->format('d.m.Y H:i') : ''}}" size="10" class="xcalend custom_style_calendar" autocomplete="off"  onClick="xCal(this)" onmouseenter="xCal(this)" onKeyUp="xCal()">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="inputZip">To date</label>
                                    <input type="text" name="to_date" value="{{isset($log) ? \Carbon\Carbon::parse($log->sort_date)->format('d.m.Y H:i') : ''}}" size="10" class="xcalend custom_style_calendar" autocomplete="off"  onClick="xCal(this)" onmouseenter="xCal(this)" onKeyUp="xCal()">
                                </div>
                            </div>

                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="inputZip">From hour</label>
                                    <input type="text" placeholder="12" name="from_hour">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="inputZip">To hour</label>
                                    <input type="text" placeholder="15" name="to_hour">
                                </div>
                            </div>
                            <input type="submit" value="Save">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        xCal("date8", {
            id: "cssworldru8", // Задать уникальный ID
            "class": "xcalend", // CSS класс оформления внешнего вида
            hide: 1, // Не скрывать календарь
            x: 0, // Отключить кнопку закрытия календаря
            autoOff: 0, // Отключить автоматическое скрытие
            to: "date8", // Разместить календарь внутри элемента с id=date8
            fn: "alert" // Вызвать функцию с указанным названием, в нее будет передан результат выбора
        });
    </script>

@endsection