routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::post('/my-logout', 'yoursessioncontroller@logout')->name('my.logout');

Route::get('/', 'HomeController@home')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/profile.html', 'HomeController@index')->name('cabinet');
    Route::get('/history.html/{paginate?}', 'HomeController@history')->name('history');
    Route::get('/business.html', 'HomeController@businessAccount')->name('business');
    Route::post('/send_preview.html', 'HomeController@payment')->name('payment');
    Route::post('/send_money.html', 'HomeController@editPayment')->name('edit');
    Route::get('/send_money/{segment2}', 'HomeController@sendInternPayment')->name('send_intern');
    Route::post('/result.html', 'HomeController@runPayment')->name('run.payment');
    Route::get('/security.html', 'HomeController@security')->name('security');
    Route::post('/change_security', 'HomeController@change_security');
    Route::get('/send.html', 'HomeController@internPayment')->name('intern');

    Route::group(['prefix' => 'dashboard'], function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::get('/account', 'DashboardController@account')->name('account');
        Route::get('/info-edit/{user}', 'DashboardController@editInfo')->name('info.edit');
        Route::post('/update-info', 'DashboardController@updateInfo')->name('update.info');
        Route::resource('wallet', 'DashboardController');
        Route::resource('log', 'LogController');
        Route::get('create-range', 'LogController@createRange')->name('log.create.range');
        Route::post('store-range', 'LogController@storeRange')->name('store.range');
        Route::get('clear-all-history', 'LogController@clear')->name('log.clear.all');
    });
	
	Route::post('/edit-wrn', 'DashboardController@updateWrn');		
	
});

app/Wallet.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Wallet extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'type_id',
        'amount',
        'status',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function type()
    {
        return $this->hasOne(WalletType::class, 'id', 'type_id');
    }
}

app/WalletType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class WalletType extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title'
    ];
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Wallet;
use App\WalletType;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class DashboardController extends Controller
{
    public function index()
    {
        $wallets = Wallet::all();

        return view('dashboard.index', compact('wallets'));
    }

    public function create()
    {
        $type = WalletType::pluck('title', 'id');

        return view('dashboard.wallet.form', compact('type'));
    }

    public function store(Request $request)
    {
        Wallet::create([
            'title' => $request->title,
            'amount' => $request->amount,
            'type_id' => $request->type,
            'status' => isset($request->status) ? 1 : 0,

        ]);

        return redirect()->route('dashboard');
    }

    public function update(Request $request, Wallet $wallet)
    {
        $wallet->update([
            'title' => $request->title,
            'amount' => $request->amount,
            'type_id' => $request->type,
            'status' => isset($request->status) ? 1 : 0,
        ]);

        return redirect()->route('dashboard');
    }

    public function edit(Wallet $wallet)
    {
        $type = WalletType::pluck('title', 'id');

        return view('dashboard.wallet.form', compact('type', 'wallet'));
    }

    public function destroy(Wallet $wallet)
    {
        $wallet->delete();

        return redirect()->route('dashboard');
    }

    public function account()
    {
        $user = User::first();
        $status = DB::table('wallet_status')->first();
		$wrn_status = DB::table('wrn_message')->first();

        return view('dashboard.info', compact('user', 'status', 'wrn_status'));
    }

    public function editInfo(User $user)
    {
        $status = DB::table('wallet_status')->first();

        return view('dashboard.edit', compact('user', 'status'));
    }

    public function updateInfo(Request $request)
    {
        $user = User::first();

        $user->update([
            'first_name' => $request->first_name,
            'last_name' => $request->last_name,
            'father_name' => $request->father_name,
            'trust_score' => $request->trust_score,
            'nickname_client' => $request->nickname_client,
            'business_account' => isset($request->business_account) ? $request->business_account : 0,
            'verified_account' => isset($request->verified_account) ? $request->verified_account : 0,
        ]);

        DB::table('wallet_status')->update([
            'business_account' => isset($request->business_account_w) ? $request->business_account_w : 0,
            'verified_account' => isset($request->verified_account_w) ? $request->verified_account_w : 0,
            'trust_score' => $request->trust_score_w,
        ]);

        return redirect()->route('account');
    }
    public function updateWrn(Request $request)
    {
        $wrn = DB::table('wrn_message')->first();
		
        (int)$wrn->wrn == 1 ? $new_status = 0 : $new_status = 1;

        DB::table('wrn_message')->update([
            'wrn' => $new_status
        ]);
		
		return response()->json(array('response'=>true));		
    }
}

app/Http/Controllers/WalletController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class WalletController extends Controller
{
    //
}

resources/views/dashboard/wallet/form.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body">
                        <form method="post"
                              action="{{isset($wallet) ? route('wallet.update', ['id' => $wallet->id]) : route('wallet.store')}}">
                            @csrf
                            @if(isset($wallet))
                                @method('put')
                            @endif
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="inputCity">Number</label>
                                    <input type="text" value="{{isset($wallet) ? $wallet->title : ''}}" maxlength="9"
                                           minlength="9" class="form-control" name="title" id="inputCity" required>
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="inputState">Type</label>
                                    <select id="inputState" name="type" class="form-control" required>
                                        <option selected value="{{null}}">Choose...</option>
                                        @foreach($type as $id => $title)
                                            <option value="{{$id}}" {{isset($wallet) ? (($wallet->type_id==$id) ? 'selected' : '') : ""}}>{{$title}}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group col-md-2">
                                    <label for="inputZip">Amount</label>
                                    <input type="text" value="{{isset($wallet) ? $wallet->amount : ''}}" name="amount"
                                           class="form-control" id="inputZip" required>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-2">
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" name="status" value="{{isset($wallet) ? $wallet->status : 0}}" {{isset($wallet) ? (($wallet->status==1) ? 'checked' : '') : ''}} >
                                        <label>Status</label>
                                    </div>
                                </div>
                            </div>

                            <input type="submit" value="Save">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection