routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::post('/my-logout', 'yoursessioncontroller@logout')->name('my.logout');

Route::get('/', 'HomeController@home')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/profile.html', 'HomeController@index')->name('cabinet');
    Route::get('/history.html/{paginate?}', 'HomeController@history')->name('history');
    Route::get('/business.html', 'HomeController@businessAccount')->name('business');
    Route::post('/send_preview.html', 'HomeController@payment')->name('payment');
    Route::post('/send_money.html', 'HomeController@editPayment')->name('edit');
    Route::get('/send_money/{segment2}', 'HomeController@sendInternPayment')->name('send_intern');
    Route::post('/result.html', 'HomeController@runPayment')->name('run.payment');
    Route::get('/security.html', 'HomeController@security')->name('security');
    Route::post('/change_security', 'HomeController@change_security');
    Route::get('/send.html', 'HomeController@internPayment')->name('intern');

    Route::group(['prefix' => 'dashboard'], function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::get('/account', 'DashboardController@account')->name('account');
        Route::get('/info-edit/{user}', 'DashboardController@editInfo')->name('info.edit');
        Route::post('/update-info', 'DashboardController@updateInfo')->name('update.info');
        Route::resource('wallet', 'DashboardController');
        Route::resource('log', 'LogController');
        Route::get('create-range', 'LogController@createRange')->name('log.create.range');
        Route::post('store-range', 'LogController@storeRange')->name('store.range');
        Route::get('clear-all-history', 'LogController@clear')->name('log.clear.all');
    });
	
	Route::post('/edit-wrn', 'DashboardController@updateWrn');		
	
});

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Wallet;
use App\WalletType;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class DashboardController extends Controller
{
    public function index()
    {
        $wallets = Wallet::all();

        return view('dashboard.index', compact('wallets'));
    }

    public function create()
    {
        $type = WalletType::pluck('title', 'id');

        return view('dashboard.wallet.form', compact('type'));
    }

    public function store(Request $request)
    {
        Wallet::create([
            'title' => $request->title,
            'amount' => $request->amount,
            'type_id' => $request->type,
            'status' => isset($request->status) ? 1 : 0,

        ]);

        return redirect()->route('dashboard');
    }

    public function update(Request $request, Wallet $wallet)
    {
        $wallet->update([
            'title' => $request->title,
            'amount' => $request->amount,
            'type_id' => $request->type,
            'status' => isset($request->status) ? 1 : 0,
        ]);

        return redirect()->route('dashboard');
    }

    public function edit(Wallet $wallet)
    {
        $type = WalletType::pluck('title', 'id');

        return view('dashboard.wallet.form', compact('type', 'wallet'));
    }

    public function destroy(Wallet $wallet)
    {
        $wallet->delete();

        return redirect()->route('dashboard');
    }

    public function account()
    {
        $user = User::first();
        $status = DB::table('wallet_status')->first();
		$wrn_status = DB::table('wrn_message')->first();

        return view('dashboard.info', compact('user', 'status', 'wrn_status'));
    }

    public function editInfo(User $user)
    {
        $status = DB::table('wallet_status')->first();

        return view('dashboard.edit', compact('user', 'status'));
    }

    public function updateInfo(Request $request)
    {
        $user = User::first();

        $user->update([
            'first_name' => $request->first_name,
            'last_name' => $request->last_name,
            'father_name' => $request->father_name,
            'trust_score' => $request->trust_score,
            'nickname_client' => $request->nickname_client,
            'business_account' => isset($request->business_account) ? $request->business_account : 0,
            'verified_account' => isset($request->verified_account) ? $request->verified_account : 0,
        ]);

        DB::table('wallet_status')->update([
            'business_account' => isset($request->business_account_w) ? $request->business_account_w : 0,
            'verified_account' => isset($request->verified_account_w) ? $request->verified_account_w : 0,
            'trust_score' => $request->trust_score_w,
        ]);

        return redirect()->route('account');
    }
    public function updateWrn(Request $request)
    {
        $wrn = DB::table('wrn_message')->first();
		
        (int)$wrn->wrn == 1 ? $new_status = 0 : $new_status = 1;

        DB::table('wrn_message')->update([
            'wrn' => $new_status
        ]);
		
		return response()->json(array('response'=>true));		
    }
}

resources/views/dashboard/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body">
                        <form method="post" action="{{route('update.info', ['id' => $user->id])}}">
                            @csrf
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <label for="inputCity">First name</label>
                                    <input type="text" value="{{$user->first_name}}"
                                           class="form-control" name="first_name" id="inputCity" required>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="inputCity">Last name</label>
                                    <input type="text" value="{{$user->last_name}}"
                                           class="form-control" name="last_name" id="inputCity" required>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="inputCity">Father name</label>
                                    <input type="text" value="{{$user->father_name}}"
                                           class="form-control" name="father_name" id="inputCity" required>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="inputCity">Trust score</label>
                                    <input type="text" value="{{$user->trust_score}}"
                                           class="form-control" name="trust_score" id="inputCity" required>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <div class="custom-control custom-checkbox" style="padding-left: 0rem;">
                                        <input type="checkbox" name="business_account"
                                               value="1" {{isset($user) ? (($user->business_account==1) ? 'checked' : '') : ''}} >
                                        <label>Business account</label>
                                    </div>
                                </div>
                                <div class="form-group col-md-3">
                                    <div class="custom-control custom-checkbox" style="padding-left: 0rem;">
                                        <input type="checkbox" name="verified_account"
                                               value="1" {{isset($user) ? (($user->verified_account==1) ? 'checked' : '') : ''}} >
                                        <label>Verified account</label>
                                    </div>
                                </div>
							</div>	
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <label for="inputCity">Nickname client</label>
                                    <input type="text" value="{{$user->nickname_client}}"
                                           class="form-control" name="nickname_client" id="inputCity" required>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="inputCity">Trust score</label>
                                    <input type="text" value="{{$status->trust_score}}"
                                           class="form-control" name="trust_score_w" id="inputCity" required>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <div class="custom-control custom-checkbox" style="padding-left: 0rem;">
                                        <input type="checkbox" name="business_account_w"
                                               value="1" {{isset($status) ? (($status->business_account==1) ? 'checked' : '') : ''}} >
                                        <label>Business account</label>
                                    </div>
                                </div>
                                <div class="form-group col-md-3">
                                    <div class="custom-control custom-checkbox" style="padding-left: 0rem;">
                                        <input type="checkbox" name="verified_account_w"
                                               value="1" {{isset($status) ? (($status->verified_account==1) ? 'checked' : '') : ''}} >
                                        <label>Verified account</label>
                                    </div>
                                </div>
							</div>	

                            <input type="submit" value="Save">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body">
                        <table class="table table-hover table-dark">
                            <thead>
                            <tr>
                                <th scope="col">Title</th>
                                <th scope="col">Type</th>
                                <th scope="col">Amount</th>
                                <th scope="col">Status</th>
                                <th scope="col" colspan="2">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($wallets as $wallet)
                                <tr>
                                    <td>{{$wallet->title}}</td>
                                    <td>{{$wallet->type->title}}</td>
                                    <td>{{$wallet->amount}}</td>
                                    <td>{{($wallet->status==1) ? 'Active' : 'Disabled'}}</td>
                                    <td><a class="btn btn-warning" href="{{route('wallet.edit', ['id' => $wallet->id])}}">Edit</a></td>
                                    <td>
                                        <form id="delete_form_project{{$wallet->id}}" method="post"
                                              action="{{route('wallet.destroy', ['wallet' => $wallet->id])}}">
                                            @method('DELETE')
                                            @csrf
                                            <a class="btn btn-danger" style="cursor: pointer"
                                               onclick="document.getElementById('delete_form_project{{$wallet->id}}').submit()">Delete</a>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/info.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body">
                        <table class="table table-hover table-dark">
                            <thead>
                            <tr>
                                <th scope="col">First name</th>
                                <th scope="col">Last name</th>
                                <th scope="col">Father name</th>
                                <th scope="col">Business account</th>
                                <th scope="col">Verified account</th>
                                <th scope="col">Trust score</th>
                                <th scope="col">Nickname client</th>
                                <th scope="col">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>{{$user->first_name}}</td>
                                <td>{{$user->last_name}}</td>
                                <td>{{$user->father_name}}</td>
                                <td>{{($user->business_account==1) ? 'Active' : 'Disabled'}}</td>
                                <td>{{($user->verified_account==1) ? 'Active' : 'Disabled'}}</td>
                                <td>{{$user->trust_score}}</td>
                                <td>{{$user->nickname_client}}</td>
                                <td><a class="btn btn-warning"
                                       href="{{route('info.edit', ['id' => $user->id])}}">Edit</a></td>
                            </tr>
                            </tbody>
                        </table>
                    </div>

					<div class="form-group col-md-12">
						<div class="custom-control custom-checkbox" style="padding-left: 0.4rem;">
							<input type="checkbox" name="wrn" id="wrn" onclick="EditWrn();" {{(int)$wrn_status->wrn == 1 ? 'checked' : ''}}>
							<label>Активировать предостережение</label>
						</div>
					</div>
					
                </div>
            </div>
        </div>
    </div>
@endsection

<script>

function EditWrn()
{
	$.ajax( "{{ action('DashboardController@updateWrn') }}", {
		type: "POST",
		data: {
			
		},
		dataType: "json",
		
		success: function(res) {

			alert('Изменения успешно сохранены!');

		},
		error: function (error) {
				
			alert('SERVER ERROR!');
			
		}
	});
}

</script>