routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::post('/my-logout', 'yoursessioncontroller@logout')->name('my.logout');

Route::get('/', 'HomeController@home')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/profile.html', 'HomeController@index')->name('cabinet');
    Route::get('/history.html/{paginate?}', 'HomeController@history')->name('history');
    Route::get('/business.html', 'HomeController@businessAccount')->name('business');
    Route::post('/send_preview.html', 'HomeController@payment')->name('payment');
    Route::post('/send_money.html', 'HomeController@editPayment')->name('edit');
    Route::get('/send_money/{segment2}', 'HomeController@sendInternPayment')->name('send_intern');
    Route::post('/result.html', 'HomeController@runPayment')->name('run.payment');
    Route::get('/security.html', 'HomeController@security')->name('security');
    Route::post('/change_security', 'HomeController@change_security');
    Route::get('/send.html', 'HomeController@internPayment')->name('intern');

    Route::group(['prefix' => 'dashboard'], function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::get('/account', 'DashboardController@account')->name('account');
        Route::get('/info-edit/{user}', 'DashboardController@editInfo')->name('info.edit');
        Route::post('/update-info', 'DashboardController@updateInfo')->name('update.info');
        Route::resource('wallet', 'DashboardController');
        Route::resource('log', 'LogController');
        Route::get('create-range', 'LogController@createRange')->name('log.create.range');
        Route::post('store-range', 'LogController@storeRange')->name('store.range');
        Route::get('clear-all-history', 'LogController@clear')->name('log.clear.all');
    });
	
	Route::post('/edit-wrn', 'DashboardController@updateWrn');		
	
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="{{ asset('js/calendar.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="#" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('my.logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('my.logout') }}" method="POST"
                                      style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-auto">
                    <div class="card">

                        <div class="card-body">
                            <div class="accordion" id="accordionExample">
                                <div class="card">
                                    <div class="card-header" id="headingOne">
                                        <h5 class="mb-0">
                                            <button class="btn btn-light" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                                Account
                                            </button>
                                        </h5>
                                    </div>

                                    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                                        <div class="card-body">
                                            <div class="btn-group-vertical">
                                                <a class="btn btn-outline-secondary" href="{{ route('account') }}">Account</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="card">
                                    <div class="card-header" id="headingTwo">
                                        <h5 class="mb-0">
                                            <button class="btn btn-light" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                                Wallet
                                            </button>
                                        </h5>
                                    </div>
                                    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                                        <div class="card-body">
                                            <div class="btn-group-vertical">
                                                <a class="btn btn-outline-secondary" href="{{ route('dashboard') }}">List Wallets</a>
                                                <a class="btn btn-outline-secondary" href="{{ route('wallet.create') }}">Create Wallet</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="card">
                                    <div class="card-header" id="headingThree">
                                        <h5 class="mb-0">
                                            <button class="btn btn-light" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                                History
                                            </button>
                                        </h5>
                                    </div>
                                    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                                        <div class="card-body">
                                            <div class="btn-group-vertical">
                                                <a class="btn btn-outline-secondary" href="{{route('log.index')}}">List History</a>
                                                <a class="btn btn-outline-secondary" href="{{route('log.create')}}">Create Actions in history</a>
                                                <a class="btn btn-outline-secondary" href="{{route('log.create.range')}}">Create Actions for date range</a>
                                                <a class="btn btn-outline-secondary" href="{{route('log.clear.all')}}">Clear all history</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-header">
                                <a class="btn btn-danger" href="{{ route('my.logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-auto">
                    @yield('content')
                </div>
            </div>
        </div>
    </main>
</div>
</body>
</html>